# Board settings

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 900

BLOCK_WIDTH = BLOCK_HEIGHT = 30
BOARD_WIDTH_BLK = 10

BOARD_HEIGHT_BLK = 20
BOARD_WIDTH_PIX = BLOCK_WIDTH * BOARD_WIDTH_BLK
BOARD_HEIGHT_PIX = BLOCK_HEIGHT * BOARD_HEIGHT_BLK
BOARD_TOP_LEFT = ((SCREEN_WIDTH - BOARD_WIDTH_PIX) / 2, (SCREEN_HEIGHT - BOARD_HEIGHT_PIX) / 2)
BOARD_BORDER_WIDTH = 5

# Display settings

FPS = 60

# Colours

BLACK = '#000000'
WHITE = '#FFFFFF'
PURPLE = '#912BAD'
RED = '#AB1517'
GREEN = '#1D8027'
LIGHT_BLUE = '#5BABD4'
DARK_BLUE = '#1A17A6'
ORANGE = '#D65B0F'
YELLOW = '#C3C916'
